[platformio]
src_dir = .

[env:genericSTM32F103ZE]
platform = ststm32
board = genericSTM32F103ZE

upload_protocol = cmsis-dap
debug_tool = cmsis-dap

board_build.ldscript = CMSIS/STM32F103ZE_FLASH.ld

build_flags =
    -D STM32F10X_HD
    -D USE_STDPERIPH_DRIVER
    --specs=nano.specs
    --specs=nosys.specs

    -I USER
    -I USER/lcd
    -I USER/font
    -I CMSIS
    -I FWlib/inc

build_src_filter =
    +<USER/*.c>
    +<USER/lcd/bsp_ili9341_lcd.c>
    +<USER/font/*.c>
    +<FWlib/src/*.c>
    +<CMSIS/system_stm32f10x.c>
    +<CMSIS/startup/startup_stm32f10x_hd_gcc.s>
    -<CMSIS/sys.c>

monitor_speed = 9600